rubytogether:
  slack: https://rubytogether.slack.com/services/hooks/heroku?token=<%= ENV.fetch("SLACK_API_TOKEN") %>
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%= ENV.fetch("ROLLBAR_API_TOKEN") %>&environment=production
rubytogether-staging:
  slack: https://rubytogether.slack.com/services/hooks/heroku?token=<%= ENV.fetch("SLACK_API_TOKEN") %>
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%= ENV.fetch("ROLLBAR_API_TOKEN_STAGING") %>&environment=production
